### ISSUE TITLE
atto_wiris (latest) appears to be missaving the txt format with MathML equations

### ISSUE THREAD

**Issue by dustinbrisebois** [wiris/moodle-atto_wiris#53]
We are seein cases where users with latest atto_wiris plugins attempt to add a MathML equation (all other pieces work as expected)

The format then returns (in preview) 

�math xmlns=�http://www.w3.org/1998/Math/MathML���msqrt��mn�2�/mn��/msqrt��/math�

where its not renderable and is deleted by the atto engine.

**Comment by manuelwiris** [comment]
Hi @dustinbrisebois 

Could you try to explain, step by step, the issue? We aren't able to reproduce it in our end. C

This plugin doesn't store MathML but a codification of MathML because Moodle doesn't allow MathML code if "Trusted content" is disabled, which is by default.  Did you change any configuration key in the plugin? 

Thanks for your feedback
